#!/usr/bin/env python3
from __future__ import annotations

import base64
import json
import re
from pathlib import Path
from urllib.parse import urlparse


ROOT = Path(__file__).resolve().parents[1]
NODES_FILE = ROOT / "data" / "nodes.json"
SETTINGS_FILE = ROOT / "data" / "settings.json"
OUT_DIR = ROOT / "data" / "caddy"
OUT_FILE = OUT_DIR / "nodes.caddy"
SAFE_ID = re.compile(r"[^A-Za-z0-9_]")


def route_name(node_id: str) -> str:
    return SAFE_ID.sub("_", node_id)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    mode = json.loads(SETTINGS_FILE.read_text()).get("mode") if SETTINGS_FILE.exists() else None
    if mode != "controller" or not NODES_FILE.exists():
        OUT_FILE.write_text("# no remote nodes configured\n")
        return

    nodes = json.loads(NODES_FILE.read_text())
    lines = ["# generated by scripts/render_caddy_nodes.py"]
    for raw in nodes:
        node_id = str(raw["id"]).strip()
        parsed = urlparse(str(raw["base_url"]).strip())
        host = parsed.hostname
        port = parsed.port or (443 if parsed.scheme == "https" else 80)
        if not host:
            raise SystemExit(f"node {node_id} missing base_url host")

        name = route_name(node_id)
        lines.extend(
            [
                f"@node_{name}_ttyd path_regexp node_{name}_ttyd ^/node-ttyd/{node_id}/(77[0-9][0-9])(/.*)?$",
                f"handle @node_{name}_ttyd {{",
                f"\trewrite * /ttyd/{{re.node_{name}_ttyd.1}}{{re.node_{name}_ttyd.2}}",
                f"\treverse_proxy {host}:{port} {{",
            ]
        )

        token = str(raw.get("token", "")).strip()
        if token:
            auth = base64.b64encode(f"admin:{token}".encode()).decode()
            lines.append(f'\t\theader_up Authorization "Basic {auth}"')

        lines.extend(["\t}", "}", ""])

    OUT_FILE.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
